apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app-project
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask-app-project
  template:
    metadata:
      labels:
        app: flask-app-project
    spec:
      containers:
        - name: flask-container
          image: amckee457/flask-app-project:latest
          ports:
            - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
